apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-v2
  labels:
    app: web
    env: dev
    tier: frontend
spec:
  containers:
  - name: nginx-container
    image: nginx:1.24
    ports:
    - containerPort: 80
